module.exports = {
  coverageDirectory: './tests/coverage/',
  collectCoverage: true,
  collectCoverageFrom: [
    '<rootDir>/src/**/*.ts',
    '!**/node_modules/**',
    '!<rootDir>/src/core/**',
    '!<rootDir>/src/models/**',
    '!<rootDir>/src/repository/**',
    '!<rootDir>/src/utils/**',
    '!<rootDir>/src/app/index.ts',
  ],
  forceExit: true,
  preset: 'ts-jest',
  roots: ['<rootDir>/tests'],
  transform: {
    '^.+\\.(ts|tsx)?$': 'ts-jest',
    '^.+\\.(js|jsx)$': 'babel-jest',
  },
  testMatch: ['**/__tests__/**/*.(js|ts|tsx)', '**/?(*.)+(spec|test).(js|ts|tsx)'],
  moduleNameMapper: {
    '^src/(.*)': '<rootDir>/src/$1',
    '^tests/(.*)': '<rootDir>/tests/$1',
    '^container': '<rootDir>/src/container',
    '^app/(.*)$': '<rootDir>/src/app/$1',
    '^@encryption': '<rootDir>/src/encryption',
    '^@config': '<rootDir>/src/config',
    '^@domain/(.*)$': '<rootDir>/src/domain/$1',
    '^@application/(.*)$': '<rootDir>/src/application/$1',
    '^@infrastructure/(.*)$': '<rootDir>/src/infrastructure/$1',
  },
  modulePaths: [],
  moduleFileExtensions: ['ts', 'js', 'json', 'node'],
  testPathIgnorePatterns: ['<rootDir>/src/nodemailer.js', '<rootDir>/(build|node_modules)/'],
  // transformIgnorePatterns: ['<rootDir>/(src|build|node_modules)/'],
  testEnvironment: 'node',
};
